name: Deploy to GKE with Terraform

on:
  push:
    branches: [main]

jobs:
  terraform:
    runs-on: self-hosted  # Use the self-hosted runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        
      - name: Install unzip (Linux)
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./terraform
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

  deploy:
    runs-on: self-hosted
    needs: terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install gcloud and kubectl
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Deploy to GKE
        run: |-
          gcloud container clusters get-credentials my-gke-cluster --zone us-central1
          kubectl apply -f k8s/deployment.yaml
